In [35]:
import pandas as pd 
import numpy as np

In [41]:
df = pd.read_csv("mflix.embedded_movies.csv")

In [ ]:
df.shape

### First look

In [ ]:
df.head()                                                    # top rows

In [ ]:
df.tail()                                                    # bottom rows

In [ ]:
df.sample(min(5, len(df)), random_state=42)                  # random rows; min guards n>len

In [ ]:
# ALTERNATIVES 
df.head(1).T                                                  # transpose for wide data

In [ ]:
df.loc[:5, ['plot','genres[0]']]                         # slice columns of interest

In [25]:
df.isna().sum()

_id                                 0
plot                               80
genres[0]                           0
genres[1]                         105
genres[2]                         706
                                 ...
plot_embedding_voyage_4_large      80
metacritic                       2221
tomatoes.consensus               2473
tomatoes.website                 2343
tomatoes.boxOffice               2720
Length: 97, dtype: int64

In [27]:
# df.head(100).style.highlight_null(color='salmon')              # inline NaN highlight

### Structural Summary

In [ ]:
df.info(memory_usage='deep')                                  # deep = true bytes of object cols

<class 'pandas.DataFrame'>
RangeIndex: 3483 entries, 0 to 3482
Data columns (total 97 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   _id                            3483 non-null   str
 1   plot                           3403 non-null   str
 2   genres[0]                      3483 non-null   str
 3   genres[1]                      3378 non-null   str
 4   genres[2]                      2777 non-null   str
 5   runtime                        3429 non-null   float64
 6   rated                          2415 non-null   str
 7   cast[0]                        3465 non-null   str
 8   cast[1]                        3456 non-null   str
 9   cast[2]                        3443 non-null   str
 10  cast[3]                        3434 non-null   str
 11  num_mflix_comments             3483 non-null   int64
 12  poster                         3169 non-null   str
 13  title                          3483 non-null   str
 14  fullplot                       3350 non-null   str
 15  languages[0]                   3462 non-null   str
 16  languages[1]                   1136 non-null   str
 17  languages[2]                   479 non-null    str
 18  languages[3]                   183 non-null    str
 19  languages[4]                   88 non-null     str
 20  languages[5]                   26 non-null     str
 21  languages[6]                   8 non-null      str
 22  languages[7]                   4 non-null      str
 23  languages[8]                   4 non-null      str
 24  languages[9]                   2 non-null      str
 25  languages[10]                  1 non-null      str
 26  released                       3430 non-null   str
 27  directors[0]                   3432 non-null   str
 28  directors[1]                   263 non-null    str
 29  directors[2]                   45 non-null     str
 30  directors[3]                   17 non-null     str
 31  directors[4]                   11 non-null     str
 32  directors[5]                   7 non-null      str
 33  directors[6]                   5 non-null      str
 34  directors[7]                   2 non-null      str
 35  directors[8]                   1 non-null      str
 36  directors[9]                   1 non-null      str
 37  directors[10]                  1 non-null      str
 38  writers[0]                     3407 non-null   str
 39  writers[1]                     2543 non-null   str
 40  writers[2]                     1590 non-null   str
 41  writers[3]                     888 non-null    str
 42  writers[4]                     474 non-null    str
 43  writers[5]                     232 non-null    str
 44  writers[6]                     107 non-null    str
 45  writers[7]                     57 non-null     str
 46  writers[8]                     32 non-null     str
 47  writers[9]                     19 non-null     str
 48  writers[10]                    12 non-null     str
 49  writers[11]                    9 non-null      str
 50  writers[12]                    8 non-null      str
 51  writers[13]                    6 non-null      str
 52  writers[14]                    5 non-null      str
 53  writers[15]                    5 non-null      str
 54  writers[16]                    3 non-null      str
 55  writers[17]                    3 non-null      str
 56  writers[18]                    1 non-null      str
 57  writers[19]                    1 non-null      str
 58  writers[20]                    1 non-null      str
 59  writers[21]                    1 non-null      str
 60  writers[22]                    1 non-null      str
 61  writers[23]                    1 non-null      str
 62  writers[24]                    1 non-null      str
 63  awards.wins                    3483 non-null   int64
 64  awards.nominations             3483 non-null   int64
 65  awards.text                    3483 non-null   str
 66  lastupdated                    3483 non-null   str
 67  year                           3483 non-null   str
 68  imdb.rating                    3477 non-null   float64
 69  imdb.votes                     3477 non-null   float64
 70  imdb.id                        3483 non-null   int64
 71  countries[0]                   3482 non-null   str
 72  countries[1]                   994 non-null    str
 73  countries[2]                   318 non-null    str
 74  countries[3]                   103 non-null    str
 75  countries[4]                   36 non-null     str
 76  countries[5]                   10 non-null     str
 77  countries[6]                   1 non-null      str
 78  type                           3483 non-null   str
 79  tomatoes.viewer.rating         3040 non-null   float64
 80  tomatoes.viewer.numReviews     3041 non-null   float64
 81  tomatoes.viewer.meter          2777 non-null   float64
 82  tomatoes.dvd                   2469 non-null   str
 83  tomatoes.critic.rating         1819 non-null   float64
 84  tomatoes.critic.numReviews     1820 non-null   float64
 85  tomatoes.critic.meter          1820 non-null   float64
 86  tomatoes.lastUpdated           3041 non-null   str
 87  tomatoes.rotten                1820 non-null   float64
 88  tomatoes.production            2291 non-null   str
 89  tomatoes.fresh                 1820 non-null   float64
 90  plot_embedding                 3402 non-null   str
 91  plot_embedding_voyage_3_large  3403 non-null   str
 92  plot_embedding_voyage_4_large  3403 non-null   str
 93  metacritic                     1262 non-null   float64
 94  tomatoes.consensus             1010 non-null   str
 95  tomatoes.website               1140 non-null   str
 96  tomatoes.boxOffice             763 non-null    str
dtypes: float64(12), int64(4), str(81)
memory usage: 104.0 MB

In [29]:
df.info(verbose=False, memory_usage='deep')                   # collapse cols, keep memory

<class 'pandas.DataFrame'>
RangeIndex: 3483 entries, 0 to 3482
Columns: 97 entries, _id to tomatoes.boxOffice
dtypes: float64(12), int64(4), str(81)
memory usage: 104.0 MB

In [31]:
# ALTERNATIVES 
df.dtypes.value_counts()                                      # dtype mix only

str        81
float64    12
int64       4
Name: count, dtype: int64

In [33]:
pd.DataFrame({                                                # dtype + null table
    'dtype'   : df.dtypes,
    'non_null': df.notnull().sum(),
    'null'    : df.isnull().sum()
})

                                 dtype  non_null  null
_id                                str      3483     0
plot                               str      3403    80
genres[0]                          str      3483     0
genres[1]                          str      3378   105
genres[2]                          str      2777   706
...                                ...       ...   ...
plot_embedding_voyage_4_large      str      3403    80
metacritic                     float64      1262  2221
tomatoes.consensus                 str      1010  2473
tomatoes.website                   str      1140  2343
tomatoes.boxOffice                 str       763  2720

[97 rows x 3 columns]

In [38]:
# ── ERRORS & FIXES ───────────────────────────────────────────

# default memory usage (shallow)    → hides string bloat
df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 3483 entries, 0 to 3482
Data columns (total 97 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   _id                            3483 non-null   str
 1   plot                           3403 non-null   str
 2   genres[0]                      3483 non-null   str
 3   genres[1]                      3378 non-null   str
 4   genres[2]                      2777 non-null   str
 5   runtime                        3429 non-null   float64
 6   rated                          2415 non-null   str
 7   cast[0]                        3465 non-null   str
 8   cast[1]                        3456 non-null   str
 9   cast[2]                        3443 non-null   str
 10  cast[3]                        3434 non-null   str
 11  num_mflix_comments             3483 non-null   int64
 12  poster                         3169 non-null   str
 13  title                          3483 non-null   str
 14  fullplot                       3350 non-null   str
 15  languages[0]                   3462 non-null   str
 16  languages[1]                   1136 non-null   str
 17  languages[2]                   479 non-null    str
 18  languages[3]                   183 non-null    str
 19  languages[4]                   88 non-null     str
 20  languages[5]                   26 non-null     str
 21  languages[6]                   8 non-null      str
 22  languages[7]                   4 non-null      str
 23  languages[8]                   4 non-null      str
 24  languages[9]                   2 non-null      str
 25  languages[10]                  1 non-null      str
 26  released                       3430 non-null   str
 27  directors[0]                   3432 non-null   str
 28  directors[1]                   263 non-null    str
 29  directors[2]                   45 non-null     str
 30  directors[3]                   17 non-null     str
 31  directors[4]                   11 non-null     str
 32  directors[5]                   7 non-null      str
 33  directors[6]                   5 non-null      str
 34  directors[7]                   2 non-null      str
 35  directors[8]                   1 non-null      str
 36  directors[9]                   1 non-null      str
 37  directors[10]                  1 non-null      str
 38  writers[0]                     3407 non-null   str
 39  writers[1]                     2543 non-null   str
 40  writers[2]                     1590 non-null   str
 41  writers[3]                     888 non-null    str
 42  writers[4]                     474 non-null    str
 43  writers[5]                     232 non-null    str
 44  writers[6]                     107 non-null    str
 45  writers[7]                     57 non-null     str
 46  writers[8]                     32 non-null     str
 47  writers[9]                     19 non-null     str
 48  writers[10]                    12 non-null     str
 49  writers[11]                    9 non-null      str
 50  writers[12]                    8 non-null      str
 51  writers[13]                    6 non-null      str
 52  writers[14]                    5 non-null      str
 53  writers[15]                    5 non-null      str
 54  writers[16]                    3 non-null      str
 55  writers[17]                    3 non-null      str
 56  writers[18]                    1 non-null      str
 57  writers[19]                    1 non-null      str
 58  writers[20]                    1 non-null      str
 59  writers[21]                    1 non-null      str
 60  writers[22]                    1 non-null      str
 61  writers[23]                    1 non-null      str
 62  writers[24]                    1 non-null      str
 63  awards.wins                    3483 non-null   int64
 64  awards.nominations             3483 non-null   int64
 65  awards.text                    3483 non-null   str
 66  lastupdated                    3483 non-null   str
 67  year                           3483 non-null   str
 68  imdb.rating                    3477 non-null   float64
 69  imdb.votes                     3477 non-null   float64
 70  imdb.id                        3483 non-null   int64
 71  countries[0]                   3482 non-null   str
 72  countries[1]                   994 non-null    str
 73  countries[2]                   318 non-null    str
 74  countries[3]                   103 non-null    str
 75  countries[4]                   36 non-null     str
 76  countries[5]                   10 non-null     str
 77  countries[6]                   1 non-null      str
 78  type                           3483 non-null   str
 79  tomatoes.viewer.rating         3040 non-null   float64
 80  tomatoes.viewer.numReviews     3041 non-null   float64
 81  tomatoes.viewer.meter          2777 non-null   float64
 82  tomatoes.dvd                   2469 non-null   str
 83  tomatoes.critic.rating         1819 non-null   float64
 84  tomatoes.critic.numReviews     1820 non-null   float64
 85  tomatoes.critic.meter          1820 non-null   float64
 86  tomatoes.lastUpdated           3041 non-null   str
 87  tomatoes.rotten                1820 non-null   float64
 88  tomatoes.production            2291 non-null   str
 89  tomatoes.fresh                 1820 non-null   float64
 90  plot_embedding                 3402 non-null   str
 91  plot_embedding_voyage_3_large  3403 non-null   str
 92  plot_embedding_voyage_4_large  3403 non-null   str
 93  metacritic                     1262 non-null   float64
 94  tomatoes.consensus             1010 non-null   str
 95  tomatoes.website               1140 non-null   str
 96  tomatoes.boxOffice             763 non-null    str
dtypes: float64(12), int64(4), str(81)
memory usage: 104.0 MB

### Column Overview

In [42]:
summary = pd.DataFrame({
    'dtype'   : df.dtypes,                                                # column type
    'non_null': df.notnull().sum(),                                       # present count
    'null'    : df.isnull().sum(),                                        # missing count
    'null_pct': (df.isnull().mean() * 100).round(2),                      # missing %
    'n_unique': df.nunique(),                                             # cardinality
    'sample'  : [                                                         # first non-null
        df[c].dropna().iloc[0] if df[c].notna().any() else None           # guard all-NaN
        for c in df.columns
    ],
}).sort_values('null_pct', ascending=False).copy()                        # copy kills warning
display(summary)

,dtype,non_null,null,null_pct,n_unique,sample
languages[10],str,1,3482,99.97,1,Egyptian (Ancient)
writers[18],str,1,3482,99.97,1,Erdman Penner (story)
writers[21],str,1,3482,99.97,1,Vernon Stallings (story)
writers[24],str,1,3482,99.97,1,Phil Dike (story)
writers[23],str,1,3482,99.97,1,Arthur Heinemann (story)
...,...,...,...,...,...,...
type,str,3483,0,0.00,2,movie
year,str,3483,0,0.00,107,1932
lastupdated,str,3483,0,0.00,3475,2015-09-03 00:32:16.227000000
awards.text,str,3483,0,0.00,729,2 wins.
imdb.id,int64,3483,0,0.00,3359,23427

In [44]:
# ── ALTERNATIVES ─────────────────────────────────────────────
summary_vec = pd.DataFrame({                                              # vectorized
    'dtype'   : df.dtypes,
    'non_null': df.notnull().sum(),
    'null_pct': df.isnull().mean().mul(100).round(2),                     # .mul avoids align
    'n_unique': df.nunique(),
})
summary_vec

                                 dtype  non_null  null_pct  n_unique
_id                                str      3483      0.00      3483
plot                               str      3403      2.30      3280
genres[0]                          str      3483      0.00        20
genres[1]                          str      3378      3.01        20
genres[2]                          str      2777     20.27        22
...                                ...       ...       ...       ...
plot_embedding_voyage_4_large      str      3403      2.30      3296
metacritic                     float64      1262     63.77        90
tomatoes.consensus                 str      1010     71.00       965
tomatoes.website                   str      1140     67.27      1067
tomatoes.boxOffice                 str       763     78.09       567

[97 rows x 4 columns]

In [46]:
summary_vec['sample'] = [
    df[c].dropna().head(1).squeeze() if df[c].notna().any() else None     # squeeze unwraps
    for c in df.columns
]
summary_vec['sample']

_id                                                       573a1392f29313caabcd9ca6
plot                             An ambitious and near insanely violent gangste...
genres[0]                                                                   Action
genres[1]                                                                    Crime
genres[2]                                                                    Drama
                                                       ...
plot_embedding_voyage_4_large    JwBR3cq8frivvFlKgT3bk6i8WUoBvQxLTDxp3VQ8I5TGPA...
metacritic                                                                    97.0
tomatoes.consensus               Errol Flynn thrills as the legendary title cha...
tomatoes.website                 http://www.mgm.com/title_title.do?title_star=G...
tomatoes.boxOffice                                                           $8.3k
Name: sample, Length: 97, dtype: object