### Importing Libraries

In [1]:
import pandas as pd
import numpy as np

### Loading Data

In [27]:
emissions_df = pd.read_csv('historical_emissions.csv')
emissions_df.head()

,Country,Data source,Sector,Gas,Unit,2018,2017,2016,2015,2014,...,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990
0,World,CAIT,Total including LUCF,CO2,MtCO₂e,36441.55,35588.70,35160.60,34521.91,34558.59,...,24957.30,24895.32,25292.92,24214.92,23890.22,23260.29,23124.00,22988.29,23056.40,22849.92
1,China,CAIT,Total including LUCF,CO2,MtCO₂e,9663.36,9367.67,9164.21,9120.27,9184.77,...,2799.84,2882.75,2779.27,2715.50,2735.48,2414.50,2294.12,2068.77,1952.78,1823.96
2,United States,CAIT,Total including LUCF,CO2,MtCO₂e,4749.57,4581.90,4656.84,4563.52,4683.35,...,5191.66,5172.06,5129.29,4864.46,4708.31,4654.52,4581.76,4461.62,4389.50,4426.40
3,European Union (27),CAIT,Total including LUCF,CO2,MtCO₂e,2636.99,2692.12,2669.54,2321.61,2263.78,...,3079.46,3134.03,3142.23,3210.93,3113.68,3060.09,3072.40,3133.06,3247.48,3286.44
4,India,CAIT,Total including LUCF,CO2,MtCO₂e,2400.25,2267.16,2149.01,2085.38,2072.03,...,683.00,618.73,600.38,555.60,519.98,466.79,431.31,409.09,386.17,341.32

In [54]:
country_code = pd.read_csv('country_code.csv')
country_code.head()

   Unnamed: 0    Country_name code_2digit code_3digit
0           2     Afghanistan          AF         AFG
1           3   Aland Islands          AX         ALA
2           4         Albania          AL         ALB
3           5         Algeria          DZ         DZA
4           6  American Samoa          AS         ASM

In [26]:
country_df = pd.read_csv('world_country_and_usa_states_latitude_and_longitude_values.csv')
country_df.head()

,country_code,latitude,longitude,country,usa_state_code,usa_state_latitude,usa_state_longitude,usa_state
0,AD,42.546245,1.601554,Andorra,AK,63.588753,-154.493062,Alaska
1,AE,23.424076,53.847818,United Arab Emirates,AL,32.318231,-86.902298,Alabama
2,AF,33.939110,67.709953,Afghanistan,AR,35.201050,-91.831833,Arkansas
3,AG,17.060816,-61.796428,Antigua and Barbuda,AZ,34.048928,-111.093731,Arizona
4,AI,18.220554,-63.068615,Anguilla,CA,36.778261,-119.417932,California

In [8]:
emissions_df['Match_found'] = emissions_df['Country'].isin(country_df['Country_name'])

merged_df = pd.merge(
    emissions_df,
    country_df,
    left_on = 'Country',
    right_on = 'Country_name',
    how = 'left'
)

merged_df.head()

,Country,Data source,Sector,Gas,Unit,2018,2017,2016,2015,2014,...,1994,1993,1992,1991,1990,Match_found,Unnamed: 0,Country_name,code_2digit,code_3digit
0,World,CAIT,Total including LUCF,CO2,MtCO₂e,36441.55,35588.70,35160.60,34521.91,34558.59,...,23260.29,23124.00,22988.29,23056.40,22849.92,False,NaN,NaN,NaN,NaN
1,China,CAIT,Total including LUCF,CO2,MtCO₂e,9663.36,9367.67,9164.21,9120.27,9184.77,...,2414.50,2294.12,2068.77,1952.78,1823.96,True,47.0,China,CN,CHN
2,United States,CAIT,Total including LUCF,CO2,MtCO₂e,4749.57,4581.90,4656.84,4563.52,4683.35,...,4654.52,4581.76,4461.62,4389.50,4426.40,False,NaN,NaN,NaN,NaN
3,European Union (27),CAIT,Total including LUCF,CO2,MtCO₂e,2636.99,2692.12,2669.54,2321.61,2263.78,...,3060.09,3072.40,3133.06,3247.48,3286.44,False,NaN,NaN,NaN,NaN
4,India,CAIT,Total including LUCF,CO2,MtCO₂e,2400.25,2267.16,2149.01,2085.38,2072.03,...,466.79,431.31,409.09,386.17,341.32,True,104.0,India,IN,IND

In [20]:
# Method 1 
merged_df[merged_df['Match_found'] == False]['Country']

# Method 2
# merged_df[~merged_df['Match_found']]

0                                 World
2                         United States
3                   European Union (27)
7                                Russia
10                                 Iran
12     Democratic Republic of the Congo
13                          South Korea
26                              Vietnam
33                            Venezuela
50                             Tanzania
86                                Syria
88                                 Laos
100                         North Korea
118                   Republic of Congo
136                              Brunei
137                           Macedonia
166                            Eswatini
178    Saint Vincent and the Grenadines
185                          Micronesia
Name: Country, dtype: object

In [ ]:
# If you just need coordinates for countries (ignore codes entirely)
import pandas as pd

# Load data
emissions_df = pd.read_csv('historical_emissions.csv')
country_df = pd.read_csv('world_country_and_usa_states_latitude_and_longitude_values.csv')

# Simple name mapping
name_mapping = {
    'United States': 'United States',
    'Russia': 'Russia',
    'Iran': 'Iran',
    'South Korea': 'Korea (South)',
    'North Korea': 'Korea (North)',
    'Vietnam': 'Viet Nam',
    'Venezuela': 'Venezuela (Bolivarian Republic of)',
    'Tanzania': 'Tanzania, United Republic of',
    'Syria': 'Syrian Arab Republic',
    'Laos': "Lao People's Democratic Republic",
    'Brunei': 'Brunei Darussalam',
    'Macedonia': 'North Macedonia',
    'Eswatini': 'Eswatini',
    'Democratic Republic of the Congo': 'Congo (Kinshasa)',
    'Republic of Congo': 'Congo',
    'Saint Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
    'Micronesia': 'Micronesia (Federated States of)',
}

# Apply mapping
emissions_df['Standardized_Country'] = emissions_df['Country'].map(name_mapping).fillna(emissions_df['Country'])

# Merge directly
final_df = pd.merge(
    emissions_df,
    country_df,
    left_on='Standardized_Country',
    right_on='country',  # Uses the 'country' column in your coordinates dataset
    how='left'
)

# Track matches
final_df['Match_Found'] = ~final_df['latitude'].isnull()

# Save
# final_df.to_csv('final_merged_dataset.csv', index=False)
print("✅ Done! Check 'final_merged_dataset.csv'")

✅ Done! Check 'final_merged_dataset.csv'

In [56]:
final_df[final_df['latitude'].isna()]
# final_df

,Country,Data source,Sector,Gas,Unit,2018,2017,2016,2015,2014,...,Standardized_Country,country_code,latitude,longitude,country,usa_state_code,usa_state_latitude,usa_state_longitude,usa_state,Match_Found
0,World,CAIT,Total including LUCF,CO2,MtCO₂e,36441.55,35588.70,35160.60,34521.91,34558.59,...,World,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,European Union (27),CAIT,Total including LUCF,CO2,MtCO₂e,2636.99,2692.12,2669.54,2321.61,2263.78,...,European Union (27),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
12,Democratic Republic of the Congo,CAIT,Total including LUCF,CO2,MtCO₂e,603.57,603.66,603.43,604.26,606.16,...,Congo (Kinshasa),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
13,South Korea,CAIT,Total including LUCF,CO2,MtCO₂e,585.07,579.56,568.98,556.05,535.54,...,Korea (South),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
26,Vietnam,CAIT,Total including LUCF,CO2,MtCO₂e,245.36,209.66,211.70,186.54,146.44,...,VietNam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
33,Venezuela,CAIT,Total including LUCF,CO2,MtCO₂e,181.29,191.71,204.88,282.40,296.87,...,Venezuela (Bolivarian Republic of),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
41,Myanmar,CAIT,Total including LUCF,CO2,MtCO₂e,136.92,133.48,125.78,128.25,124.63,...,Myanmar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
50,Tanzania,CAIT,Total including LUCF,CO2,MtCO₂e,75.68,75.47,75.03,63.65,62.68,...,"Tanzania, United Republic of",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
86,Syria,CAIT,Total including LUCF,CO2,MtCO₂e,27.92,29.10,26.46,25.37,26.40,...,Syrian Arab Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
88,Laos,CAIT,Total including LUCF,CO2,MtCO₂e,27.46,27.18,24.03,17.32,13.09,...,Lao People's Democratic Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
100,North Korea,CAIT,Total including LUCF,CO2,MtCO₂e,21.41,25.67,33.38,28.50,34.62,...,Korea (North),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
118,Republic of Congo,CAIT,Total including LUCF,CO2,MtCO₂e,13.69,13.66,13.76,12.91,13.55,...,Congo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
126,South Sudan,CAIT,Total including LUCF,CO2,MtCO₂e,10.28,10.44,10.67,8.51,8.07,...,South Sudan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
136,Brunei,CAIT,Total including LUCF,CO2,MtCO₂e,7.47,7.03,6.79,6.35,7.37,...,Brunei Darussalam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
137,Macedonia,CAIT,Total including LUCF,CO2,MtCO₂e,7.37,7.86,7.39,7.48,7.78,...,North Macedonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
166,Eswatini,CAIT,Total including LUCF,CO2,MtCO₂e,0.96,0.91,1.10,0.90,0.83,...,Eswatini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
174,Sao Tome and Principe,CAIT,Total including LUCF,CO2,MtCO₂e,0.35,0.35,0.34,0.34,0.33,...,Sao Tome and Principe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
185,Micronesia,CAIT,Total including LUCF,CO2,MtCO₂e,0.15,0.14,0.14,0.12,0.11,...,Micronesia (Federated States of),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [4]:
import pandas as pd
import numpy as np

# ============================================
# 1. LOAD DATA
# ============================================
emissions_df = pd.read_csv('historical_emissions.csv')
country_code = pd.read_csv('country_code.csv', keep_default_na=False, na_values=[''])
country_df = pd.read_csv('world_country_and_usa_states_latitude_and_longitude_values.csv', 
                         keep_default_na=False, na_values=[''])

print("✅ Data loaded successfully")

# ============================================
# 2. CREATE SEPARATE MAPPING DICTIONARIES
# ============================================
# For coordinates dataset (country_df)
GEO_MAPPING = {
    'democratic republic of the congo': 'congo [drc]',
    'republic of congo': 'congo [republic]',
    'eswatini': 'swaziland',
    'macedonia': 'macedonia [fyrom]',
    'myanmar': 'myanmar [burma]',
}

# For country codes dataset (country_code)
CODE_MAPPING = {
    'brunei': 'brunei darussalam',
    'iran': 'iran, islamic republic of',
    'macedonia': 'macedonia, republic of',
    'micronesia': 'micronesia, federated states of',
    'north korea': 'korea (north)',
    'south korea': 'korea (south)',
    'republic of congo': 'congo (brazzaville)',
    'democratic republic of the congo': 'congo, (kinshasa)',
    'saint vincent and the grenadines': 'saint vincent and grenadines',
    'syria': 'syrian arab republic (syria)',
    'tanzania': 'tanzania, united republic of',
    'united states': 'united states of america',
    'venezuela': 'venezuela (bolivarian republic)',
    'vietnam': 'viet nam',
    'eswatini': 'swaziland',
    'russia': 'russian federation',
    'laos': 'lao pdr',
}

# ============================================
# 3. STANDARDIZE NAMES
# ============================================
# Create lowercase keys
emissions_df['_key'] = emissions_df['Country'].str.lower().str.strip()
country_df['_key'] = country_df['country'].str.lower().str.strip()
country_code['_key'] = country_code['Country_name'].str.lower().str.strip()

# Apply mappings
emissions_df['_geo_key'] = emissions_df['_key'].map(GEO_MAPPING).fillna(emissions_df['_key'])
emissions_df['_code_key'] = emissions_df['_key'].map(CODE_MAPPING).fillna(emissions_df['_key'])

# ============================================
# 4. MERGE DATA
# ============================================
# First merge: ISO codes
merged_df = emissions_df.merge(
    country_code[['_key', 'code_2digit', 'code_3digit']].rename(
        columns={'_key': '_lookup', 'code_2digit': 'iso2', 'code_3digit': 'iso3'}
    ),
    left_on='_code_key',
    right_on='_lookup',
    how='left'
).drop(columns=['_lookup'])

# Second merge: Coordinates
merged_df = merged_df.merge(
    country_df[['_key', 'latitude', 'longitude']].rename(columns={'_key': '_lookup'}),
    left_on='_geo_key',
    right_on='_lookup',
    how='left'
).drop(columns=['_lookup'])

# Clean up helper columns
merged_df = merged_df.drop(columns=['_key', '_geo_key', '_code_key'])

print("✅ Data merged successfully")

# ============================================
# 5. CHECK RESULTS FOR YOUR SPECIFIC COUNTRIES
# ============================================
# Check specific countries you mentioned
countries_to_check = [
    'World', 'United States', 'European Union (27)', 'Russia', 'Iran',
    'South Korea', 'Vietnam', 'Venezuela', 'Tanzania', 'Syria', 
    'Laos', 'North Korea', 'South Sudan', 'Brunei', 'Sao Tome and Principe',
    'Saint Vincent and the Grenadines'
]

print("\n📊 Checking specific countries:")
for country in countries_to_check:
    row = merged_df[merged_df['Country'] == country]
    if len(row) > 0:
        # FIX: Use pd.isna() instead of .isna() on individual values
        has_coords = not pd.isna(row.iloc[0]['latitude'])
        has_iso = not pd.isna(row.iloc[0]['iso2'])
        status = []
        if has_coords:
            status.append('📍')
        if has_iso:
            status.append('🏷️')
        status_str = ' '.join(status) if status else '❌'
        print(f"{status_str:6} {country}")
    else:
        print(f"❌ {country} (not found)")

# ============================================
# 6. SHOW COUNTRIES STILL MISSING COORDINATES
# ============================================
aggregates = {'world', 'european union (27)'}
missing = merged_df[
    merged_df['latitude'].isna() & 
    ~merged_df['Country'].str.lower().isin(aggregates)
]

print(f"\n📊 Missing coordinates summary:")
print(f"Total rows with missing coordinates: {merged_df['latitude'].isna().sum()}")
print(f"Countries missing coordinates (excluding aggregates): {missing['Country'].nunique()}")

if len(missing) > 0:
    print("\n⚠️ Countries still missing coordinates:")
    for country in missing['Country'].unique():
        print(f"  - {country}")

# ============================================
# 7. REORDER AND SAVE
# ============================================
year_cols = [col for col in merged_df.columns if col.isdigit()]
front_cols = ['Country', 'iso2', 'iso3', 'latitude', 'longitude']
merged_df = merged_df[front_cols + year_cols]

merged_df.to_csv('merged_country_co2_geo.csv', index=False)
print(f"\n✅ Saved to 'merged_country_co2_geo.csv'")

# Show first few rows
print("\n📋 Sample of merged data (first 5 rows):")
print(merged_df[['Country', 'iso2', 'iso3', 'latitude', 'longitude']].head())

✅ Data loaded successfully
✅ Data merged successfully

📊 Checking specific countries:
❌      World
📍 🏷️   United States
❌      European Union (27)
📍 🏷️   Russia
📍 🏷️   Iran
📍 🏷️   South Korea
📍 🏷️   Vietnam
📍 🏷️   Venezuela
📍 🏷️   Tanzania
📍 🏷️   Syria
📍 🏷️   Laos
📍 🏷️   North Korea
🏷️     South Sudan
📍 🏷️   Brunei
🏷️     Sao Tome and Principe
📍 🏷️   Saint Vincent and the Grenadines

📊 Missing coordinates summary:
Total rows with missing coordinates: 4
Countries missing coordinates (excluding aggregates): 2

⚠️ Countries still missing coordinates:
  - South Sudan
  - Sao Tome and Principe

✅ Saved to 'merged_country_co2_geo.csv'

📋 Sample of merged data (first 5 rows):
               Country iso2 iso3   latitude   longitude
0                World  NaN  NaN        NaN         NaN
1                China   CN  CHN  35.861660  104.195397
2        United States   US  USA  37.090240  -95.712891
3  European Union (27)  NaN  NaN        NaN         NaN
4                India   IN  IND  20.593684   78.962880

In [5]:
merged_df[merged_df['latitude'].isna()]

,Country,iso2,iso3,latitude,longitude,2018,2017,2016,2015,2014,...,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990
0,World,NaN,NaN,NaN,NaN,36441.55,35588.70,35160.60,34521.91,34558.59,...,24957.30,24895.32,25292.92,24214.92,23890.22,23260.29,23124.00,22988.29,23056.40,22849.92
3,European Union (27),NaN,NaN,NaN,NaN,2636.99,2692.12,2669.54,2321.61,2263.78,...,3079.46,3134.03,3142.23,3210.93,3113.68,3060.09,3072.40,3133.06,3247.48,3286.44
126,South Sudan,SS,SSD,NaN,NaN,10.28,10.44,10.67,8.51,8.07,...,7.06,7.03,7.02,7.01,7.01,6.94,6.94,6.94,6.94,6.94
174,Sao Tome and Principe,ST,STP,NaN,NaN,0.35,0.35,0.34,0.34,0.33,...,0.06,0.06,0.06,0.06,0.06,0.06,0.05,0.05,0.06,0.06

In [6]:
merged_df.sample()

,Country,iso2,iso3,latitude,longitude,2018,2017,2016,2015,2014,...,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990
75,Cambodia,KH,KHM,12.565679,104.990963,40.16,40.38,38.9,73.51,71.55,...,6.08,6.11,5.87,5.78,5.68,5.64,5.55,5.52,5.47,5.43

In [7]:
# ============================================
# ADD MANUAL COORDINATES FOR MISSING COUNTRIES
# ============================================
# Define manual coordinates for missing countries
manual_coords = {
    'South Sudan': (6.876991, 31.306978),
    'Sao Tome and Principe': (0.255436, 6.602781),
    'European Union (27)': (56.7000, 15.0000)
}

# Add coordinates to existing rows
for country, (lat, lon) in manual_coords.items():
    mask = merged_df['Country'] == country
    if mask.any():
        merged_df.loc[mask, 'latitude'] = lat
        merged_df.loc[mask, 'longitude'] = lon
        print(f"✅ Added coordinates for {country}: ({lat}, {lon})")

✅ Added coordinates for South Sudan: (6.876991, 31.306978)
✅ Added coordinates for Sao Tome and Principe: (0.255436, 6.602781)
✅ Added coordinates for European Union (27): (56.7, 15.0)

In [8]:
merged_df[merged_df['latitude'].isna()]

,Country,iso2,iso3,latitude,longitude,2018,2017,2016,2015,2014,...,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990
0,World,NaN,NaN,NaN,NaN,36441.55,35588.7,35160.6,34521.91,34558.59,...,24957.3,24895.32,25292.92,24214.92,23890.22,23260.29,23124.0,22988.29,23056.4,22849.92