In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("Week1_GA_dataset.csv")

In [4]:
df.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

### Question 1

In [5]:
df.isna().sum()

Date                    0
Year                    0
Locality             1253
Estimated Value      1243
Sale Price              0
Property                0
Residential             0
num_rooms               0
num_bathrooms           0
carpet_area          1229
property_tax_rate       0
Face                    0
dtype: int64

In [6]:
df.isin(['?']).sum()

Date                    0
Year                    0
Locality                0
Estimated Value         0
Sale Price              0
Property             1823
Residential             0
num_rooms               0
num_bathrooms           0
carpet_area             0
property_tax_rate       0
Face                    0
dtype: int64

### Question 2

In [7]:
df.shape

(10000, 12)

### Question 3

In [8]:
df.iloc[692, 0]

'2009-11-16'

### Question 4

In [9]:
df.iloc[546, 7]

np.int64(3)

### Question5

In [10]:
df.Locality.unique()

<ArrowStringArray>
[    'Waterbury',    'Bridgeport',     'Greenwich',       'Norwalk',
             nan,     'Fairfield', 'West Hartford',      'Stamford']
Length: 8, dtype: str

### Question 6

In [11]:
df.replace('?', np.nan, inplace=True)

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,NaN,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,NaN,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,NaN,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [12]:
df.isna().sum()

Date                    0
Year                    0
Locality             1253
Estimated Value      1243
Sale Price              0
Property             1823
Residential             0
num_rooms               0
num_bathrooms           0
carpet_area          1229
property_tax_rate       0
Face                    0
dtype: int64

In [13]:
df.isin(['?']).sum()

Date                 0
Year                 0
Locality             0
Estimated Value      0
Sale Price           0
Property             0
Residential          0
num_rooms            0
num_bathrooms        0
carpet_area          0
property_tax_rate    0
Face                 0
dtype: int64

### Question 7

In [14]:
df.isna().sum().sort_values(ascending=False)

Property             1823
Locality             1253
Estimated Value      1243
carpet_area          1229
Date                    0
Year                    0
Residential             0
Sale Price              0
num_rooms               0
num_bathrooms           0
property_tax_rate       0
Face                    0
dtype: int64

### Question 8

In [15]:
df.dropna(thresh=10, inplace = True)

In [16]:
df.shape

(9917, 12)

### Question 9

In [17]:
df.dropna(inplace=True)

In [18]:
df.shape

(5449, 12)

In [19]:
df.isna().sum()

Date                 0
Year                 0
Locality             0
Estimated Value      0
Sale Price           0
Property             0
Residential          0
num_rooms            0
num_bathrooms        0
carpet_area          0
property_tax_rate    0
Face                 0
dtype: int64

## Graded 2

In [20]:
df = pd.read_csv('Week1_GA_dataset.csv')

In [21]:
df.shape

(10000, 12)

In [22]:
# dataframe with even number of index
df2 = df.loc[::2]

### Question 1

In [23]:
df2.iloc[0, 3]

np.float64(111440.0)

### Question 2

In [24]:
df2.iloc[332, 3]

np.float64(256200.0)

### Question 3

In [47]:
# dataframe with odd number of index
df3 = df.loc[1::2]

In [26]:
df3.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
5,2009-01-02,2009,Greenwich,2868880.0,3300000.0,Single Family,Detached House,3,1,1039.0,1.025953,North
7,2009-01-02,2009,Greenwich,592760.0,920000.0,Single Family,Detached House,3,3,937.0,1.025953,North
9,2009-01-02,2009,Bridgeport,137901.0,245000.0,Single Family,Detached House,3,1,956.0,1.025953,West

In [27]:
df3.iloc[332, 3]

np.float64(352940.0)

### Question 4

In [51]:
df.iloc[:, 1::2].iloc[100, 5]

'West'

### Question 5

In [29]:
# df = pd.read_csv("Week1_GA_dataset.csv")

In [30]:
# all even rows, all even index
df4 = df.iloc[::2,::2]

In [31]:
df4.head(3)

,Date,Locality,Sale Price,Residential,num_bathrooms,property_tax_rate
0,2009-01-02,Waterbury,185000.0,Detached House,3,1.025953
2,2009-01-02,Waterbury,140000.0,Detached House,2,1.025953
4,2009-01-02,Bridgeport,210000.0,Detached House,2,1.025953

In [32]:
df4.iloc[255, 3]

'Detached House'

### Question 6

In [73]:
year_list = df['Year'].unique()
year_list = year_list[-6:]
year_list

array([2017, 2018, 2019, 2020, 2021, 2022])

In [77]:
df[df['Year'].isin(year_list)].shape

(4749, 13)

### Question 7

In [34]:
df.columns

Index(['Date', 'Year', 'Locality', 'Estimated Value', 'Sale Price', 'Property',
       'Residential', 'num_rooms', 'num_bathrooms', 'carpet_area',
       'property_tax_rate', 'Face'],
      dtype='str')

In [35]:
df[(df['num_bathrooms'] == 3) & (df['num_rooms'] == 3)]

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
7,2009-01-02,2009,Greenwich,592760.0,920000.0,Single Family,Detached House,3,3,937.0,1.025953,North
13,2009-01-03,2009,Greenwich,1046920.0,600000.0,Single Family,Detached House,3,3,1068.0,1.025953,South
16,2009-01-05,2009,Waterbury,74620.0,206500.0,Single Family,Detached House,3,3,966.0,1.025953,South
22,2009-01-08,2009,NaN,1260560.0,1895000.0,Single Family,Detached House,3,3,1005.0,1.025953,South
...,...,...,...,...,...,...,...,...,...,...,...,...
9989,2022-09-29,2022,Stamford,373530.0,485000.0,?,Detached House,3,3,1084.0,1.003979,South
9990,2022-09-30,2022,NaN,352030.0,700000.0,?,Detached House,3,3,958.0,1.003979,North
9991,2022-09-30,2022,Norwalk,344270.0,512500.0,Single Family,Detached House,3,3,NaN,1.003979,West
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,?,Detached House,3,3,917.0,1.003979,North
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North

### Question 8

In [36]:
df[(df['num_bathrooms'] == 3) | (df['num_rooms'] == 3)]

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9993,2022-09-30,2022,West Hartford,121870.0,235000.0,Single Family,Detached House,3,2,1087.0,1.003979,South
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,?,Detached House,3,3,917.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

### Question 9

In [37]:
df.columns.to_list()

['Date',
 'Year',
 'Locality',
 'Estimated Value',
 'Sale Price',
 'Property',
 'Residential',
 'num_rooms',
 'num_bathrooms',
 'carpet_area',
 'property_tax_rate',
 'Face']

In [38]:
df5 = df[(df['Year'] == 2022) & (df['Locality'] == 'Greenwich') & (df['num_rooms'] == 3) & (df.Face.isin(['North', 'East']))]

In [39]:
df5.shape

(42, 12)

### Question 10

In [40]:
df.sample()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
4053,2015-06-27,2015,Norwalk,235410.0,359000.0,Single Family,Detached House,3,1,906.0,1.340225,South

In [41]:
df['Month'] = pd.to_datetime(df['Date'], format = '%Y-%m-%d')

In [42]:
df['Month'] = df['Month'].dt.month

In [43]:
df['Month'].value_counts()

Month
6     1128
8     1050
7     1045
5      924
9      838
12     821
10     784
4      737
11     726
3      721
1      631
2      595
Name: count, dtype: int64

### Question 11

In [44]:
df.columns

Index(['Date', 'Year', 'Locality', 'Estimated Value', 'Sale Price', 'Property',
       'Residential', 'num_rooms', 'num_bathrooms', 'carpet_area',
       'property_tax_rate', 'Face', 'Month'],
      dtype='str')

In [45]:
df.groupby(['Locality'])['Sale Price'].mean().sort_values(ascending=False)

Locality
Greenwich        2.270224e+06
Fairfield        7.277225e+05
Stamford         6.305313e+05
Norwalk          5.590959e+05
West Hartford    3.385472e+05
Bridgeport       1.740953e+05
Waterbury        1.062152e+05
Name: Sale Price, dtype: float64